### PR TITLE
AIRTIM1-20 Enable user login BE

### PR DESCRIPTION
**Pull request by mfric20**
Finished user registration on the backend.

### CODE REVIEW

**Review by nrisek — APPROVED** [review]
Everything looks good. Usage of JWT is good and up to standards.

**Review by StjepanCecura — APPROVED** [review]
Login works without error and sign out as well.

**Review by marijaboss — APPROVED** [review]
Tested and works successfully.

**Review by Wuljo318 — COMMENTED** [review]
Everything is ok!

**Pull request merged**
