### PR TITLE
AIRTIM1-14 enable user registration be

### PR DESCRIPTION
**Pull request by mfric20**
Completed customer registration functionality on the backend. Waiting for QA.

### CODE REVIEW

**Review by StjepanCecura — APPROVED** [review]
Tested successfully and works.

**Review by nrisek — APPROVED** [review]
User microservice is made by standards. Good folder structure and clean code. Usage of environment variables is a good choice.

**Review by Wuljo318 — APPROVED** [review]
Everything is OK.

**Review by marijaboss — APPROVED** [review]
Tested, is working correctly.

**Pull request merged**
